export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOAD_PROFILE = "LOAD_PROFILE";

export const TRANSACTIONS_REQUEST = "TRANSACTIONS_REQUEST";
export const TRANSACTIONS_SUCCESS = "TRANSACTIONS_SUCCESS";
export const TRANSACTIONS_FAIL = "TRANSACTIONS_FAIL";

export const TRANSACTION_DETAILS_REQUEST = "TRANSACTION_DETAILS_REQUEST";
export const TRANSACTION_DETAILS_SUCCESS = "TRANSACTION_DETAILS_SUCCESS";
export const TRANSACTION_DETAILS_FAIL = "TRANSACTION_DETAILS_FAIL";

export const NEW_TRANSACTION_REQUEST = "NEW_TRANSACTION_REQUEST";
export const NEW_TRANSACTION_SUCCESS = "NEW_TRANSACTION_SUCCESS";
export const NEW_TRANSACTION_FAIL = "NEW_TRANSACTION_FAIL";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const DELETE_TRANSACTION_REQUEST = "DELETE_TRANSACTION_REQUEST";
export const DELETE_TRANSACTION_SUCCESS = "DELETE_TRANSACTION_SUCCESS";
export const DELETE_TRANSACTION_FAIL = "DELETE_TRANSACTION_FAIL";

export const UPDATE_TRANSACTION_REQUEST = "UPDATE_TRANSACTION_REQUEST";
export const UPDATE_TRANSACTION_SUCCESS = "UPDATE_TRANSACTION_SUCCESS";
export const UPDATE_TRANSACTION_FAIL = "UPDATE_TRANSACTION_FAIL";

export const SET_ACTIVE_ELEMENT_REQUEST = "SET_ACTIVE_ELEMENT_REQUEST";
export const SET_ACTIVE_ELEMENT_SUCCESS = "SET_ACTIVE_ELEMENT_SUCCESS";
export const SET_ACTIVE_ELEMENT_FAIL = "SET_ACTIVE_ELEMENT_FAIL";
