export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOAD_PROFILE = "LOAD_PROFILE";

export const TRANSACTIONS_REQUEST = "TRANSACTIONS_REQUEST"
export const TRANSACTIONS_SUCCESS = "TRANSACTIONS_SUCCESS"
export const TRANSACTIONS_FAIL = "TRANSACTIONS_FAIL"

export const TRANSACTION_DETAILS_REQUEST = "TRANSACTION_DETAILS_REQUEST"
export const TRANSACTION_DETAILS_SUCCESS = "TRANSACTION_DETAILS_SUCCESS"
export const TRANSACTION_DETAILS_FAIL = "TRANSACTION_DETAILS_FAIL"